#!/bin/bash

declare -a executables=(
    "arandr"
    "autorandr"
    "brightnessctl"
    "chromium"
    "cliphist"
    "dex"
    "firefox"
    "flameshot"
    "fzf"
    "gammastep"
    "ghostty"
    "ghostty"
    "i3lock"
    "jq"
    "numlockx"
    "pip"
    "polybar"
    "pylsp"
    "rofi"
    "screenkey"
    "shikane"
    "simplescreenrecorder"
    "sway"
    "swaybg"
    "tmux"
    "udisksctl"
    "volumeicon"
    "waybar"
    "wezterm"
    "wtype"
    "x11-ssh-askpass"
    "xdotool"
    "xpanes"
    "xrandr"
    "zathura"
    #"greenclip"
)

for executable in "${executables[@]}"
do
    command -v "$executable" >/dev/null || echo "$executable is not installed";
done
