#!/bin/bash

SCRIPT_PATH=$( command -v /bin/realpath > /dev/null && /bin/realpath "${BASH_SOURCE[0]}" || /bin/readlink -f "${BASH_SOURCE[0]}" )
[ -f "${SCRIPT_PATH%/*}/../.share/common.sh" ] && . "${SCRIPT_PATH%/*}/../.share/common.sh" || exit 1

cat << 'OUT'
# SSH_AUTH_SOCK
export $(systemctl --user show-environment | grep '^SSH_AUTH_SOCK=')

OUT

printf "export DOTFILES_PATH=\"%q\"\n\n" "${DOTFILES_PATH}"

. "${DOTFILES_PATH}/lib/bash/path_augment_local.sh"
AUGMENT="$(_path_augment_local_collect "")"

if test ! -z "$AUGMENT"; then
    printf "export PATH=%q:%s\n\n" "${AUGMENT}" '$PATH'
fi

cat << 'OUT'
# TERMINAL 
export TERMINAL="$( "${DOTFILES_PATH}/bin/system/sensible-terminal" --query )"
OUT
