#!/bin/bash

SCRIPT_PATH=$( command -v /bin/realpath > /dev/null && /bin/realpath "${BASH_SOURCE[0]}" || /bin/readlink -f "${BASH_SOURCE[0]}" )
[ -f "${SCRIPT_PATH%/*}/../.share/common.sh" ] && . "${SCRIPT_PATH%/*}/../.share/common.sh" || exit 1

cd "$( dirname "${SCRIPT_PATH}" )"

printf "DOTFILES_PATH=%q\n" "${DOTFILES_PATH}"

. "${DOTFILES_PATH}/lib/bash/path_augment_local.sh"
AUGMENT="$(_path_augment_local_collect "")"

if test ! -z "$AUGMENT"; then
    printf "PATH=%q:%s\n" "${AUGMENT}" '$PATH'
fi

printf "# systemctl daemon-reload\n"
printf "# systemctl import-environment\n"
printf "# systemctl --user daemon-reload\n"
printf "# systemctl --user import-environment\n" 
