#!/bin/bash

_error_message() {
    [ -n "$1" ] && {
        echo "$1" >&2
        command -v /bin/notify-send >/dev/null && notify-send -- "$1"
    }
}

_exit() {
    [ -n "$1" ] && _error_message "$1"
    exit "${2:-1}"
}

main ()
{
    nmcli connection up {vpn} || _exit "Nu am reușit să mă conectez la {vpn}"

    ssh-ensure-key "${HOME}/.ssh/key_1" \
    && ssh-ensure-key "${HOME}/.ssh/key_2" \
    && ssh-ensure-key "${HOME}/.ssh/key_3" \
    && i3-msg 'workspace 1; exec "${HOME}/.local/bin/all-terms"' \
    && sleep 1 \
    && i3-msg 'workspace 5; exec "/usr/bin/thunderbird"' \
    && sleep 1 \
    && i3-msg 'workspace 5; exec "/usr/bin/slack"' \
    && sleep 1 \
    && i3-msg 'workspace 4; exec "${HOME}/.local/bin/sqlyog 2>/dev/null"' \
    && sleep 1 \
    && i3-msg 'workspace 3; exec "fde"' \
    && sleep 1 \
    && i3-msg 'workspace 1' 

} 

main
