for_window [app_id="xfce4-terminal"] border pixel 2
for_window [app_id="org.wezfurlong.wezterm"] border pixel 2
for_window [app_id="st"] border pixel 2
for_window [app_id="firefox-aurora"] border pixel 4
for_window [app_id="firefox-developer-edition"] border pixel 4
for_window [app_id="sqlyog.exe"] move container to workspace 4
for_window [app_id="Thunderbird"] move container to workspace 5
for_window [app_id="thunderbird"] move container to workspace 5
for_window [app_id="slack"] move container to workspace 5
for_window [app_id="Slack"] move container to workspace 5
for_window [app_id="microsoft teams - preview"] move container to workspace 5
for_window [app_id="Microsoft Teams - Preview"] move container to workspace 5
for_window [shell="xwayland"] title_format "<span>[X] %title゜</span>"
