# screen capture
# bindsym Print exec QT_SCALE_FACTOR=0.5 flameshot gui
bindsym Print exec flameshot gui

# JOT
bindsym $mod+Shift+o exec EDITOR=gvim jot

# tmux sessionizer
bindsym $mod+t exec bash "${DOTFILES_PATH}/bin/tmux-sessionizer/tmux-sessionizer.sh" > ~/tmp/_ts_o 2>~/tmp/_ts_e

# cliphist
bindsym Ctrl+$mod1+h exec bash $DOTFILES_PATH/bin/system/multi_clipboard

# de portat
# bindsym Control+Mod1+h exec --no-startup-id $DOTFILES_PATH/bin/system/multi_clipboard

# Keboard selector
# bindsym $mod+Shift+i exec --no-startup-id $DOTFILES_PATH/bin/system/keyboard_select

# Monitor layout
# bindsym $mod+Shift+p exec --no-startup-id $DOTFILES_PATH/bin/system/monitor_layout

# Autorandr
bindsym $mod+p exec $DOTFILES_PATH/bin/system/monitor_reset

# Autostart
exec dex --autostart --environment sway
